Add view with carousel
vividus-framework/vividus-test-app pull request #273
Opened 2021-08-31 14:09 UTC by ikalinin1

2021-08-31 14:11 UTC, ikalinin1 commented
![image](https://user-images.githubusercontent.com/17816729/131518046-b2d158a3-562a-40d1-986a-6da1bf18055d.png)

2021-08-31 14:57 UTC, valfirst requested changes
Conflicts require resolution

2021-09-01 06:38 UTC, valfirst approved these changes

2021-09-01 08:17 UTC, uarlouski approved these changes

2021-09-01 08:22 UTC, merged